#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: pexod/pose
        pose2d: pexod/ground_pose
        child_frame_id: pexod/base_link
        parent_frame_id: world


optitrack_config:
        multicast_address: 239.255.42.99
