#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: pexod/pose
        pose2d: pexod/ground_pose
        child_frame_id: base_link
        parent_frame_id: odom
    '2':
        pose: Robot_2/pose
        pose2d: Robot_2/ground_pose
        child_frame_id: Robot_2/base_link
        parent_frame_id: world
